import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { calcTrendScore } from "@/lib/trend-score";

const DEMO_PRODUCTS = [
  {
    name: "SKINTIFIC 5X Ceramide Barrier Moisture Gel",
    brand: "SKINTIFIC",
    subCategory: "Moisturizer",
    price: 45.9,
    gmv: 820000,
    gmvGrowthRate: 68,
    salesVolume: 17800,
    salesGrowthRate: 52,
    creatorCount: 340,
    creatorGrowthRate: 38,
    videoCount: 1200,
    viewCount: 45000000,
    primaryKeyword: "ceramide moisturizer",
    keywords: '["ceramide","barrier repair","skintific","moisturizer"]',
    searchVolume: 48000,
    searchTrend: "rising",
    sellerCount: 28,
    imageUrl: "https://placehold.co/400x400/f0fdf4/16a34a?text=SKINTIFIC",
  },
  {
    name: "Pinkflash OhMyGloss Water Lip Gloss",
    brand: "Pinkflash",
    subCategory: "Lip Makeup",
    price: 12.9,
    gmv: 390000,
    gmvGrowthRate: 85,
    salesVolume: 30200,
    salesGrowthRate: 71,
    creatorCount: 820,
    creatorGrowthRate: 44,
    videoCount: 3400,
    viewCount: 88000000,
    primaryKeyword: "lip gloss tiktok",
    keywords: '["lip gloss","pinkflash","glowy lips","affordable makeup"]',
    searchVolume: 35000,
    searchTrend: "rising",
    sellerCount: 45,
    imageUrl: "https://placehold.co/400x400/fff0f6/db2777?text=Pinkflash",
  },
  {
    name: "FOCALLURE Eyeshadow Palette 18 Colors",
    brand: "FOCALLURE",
    subCategory: "Eye Makeup",
    price: 38.0,
    gmv: 560000,
    gmvGrowthRate: 32,
    salesVolume: 14700,
    salesGrowthRate: 28,
    creatorCount: 510,
    creatorGrowthRate: 19,
    videoCount: 2800,
    viewCount: 62000000,
    primaryKeyword: "eyeshadow palette",
    keywords: '["eyeshadow","palette","focallure","eye makeup"]',
    searchVolume: 29000,
    searchTrend: "stable",
    sellerCount: 62,
    imageUrl: "https://placehold.co/400x400/fefce8/ca8a04?text=FOCALLURE",
  },
  {
    name: "Hold Live Velvet Matte Lip Mud",
    brand: "Hold Live",
    subCategory: "Lip Makeup",
    price: 22.5,
    gmv: 240000,
    gmvGrowthRate: 112,
    salesVolume: 10700,
    salesGrowthRate: 95,
    creatorCount: 190,
    creatorGrowthRate: 72,
    videoCount: 680,
    viewCount: 22000000,
    primaryKeyword: "matte lip mud",
    keywords: '["lip mud","matte lips","hold live","korean makeup"]',
    searchVolume: 18000,
    searchTrend: "rising",
    sellerCount: 15,
    imageUrl: "https://placehold.co/400x400/fdf4ff/a21caf?text=HoldLive",
  },
  {
    name: "Bioaqua Pearl Brightening BB Cream",
    brand: "Bioaqua",
    subCategory: "Foundation",
    price: 18.9,
    gmv: 680000,
    gmvGrowthRate: 8,
    salesVolume: 36000,
    salesGrowthRate: 5,
    creatorCount: 1200,
    creatorGrowthRate: 3,
    videoCount: 5600,
    viewCount: 130000000,
    primaryKeyword: "bb cream malaysia",
    keywords: '["bb cream","bioaqua","foundation","brightening"]',
    searchVolume: 55000,
    searchTrend: "stable",
    sellerCount: 180,
    imageUrl: "https://placehold.co/400x400/eff6ff/2563eb?text=Bioaqua",
  },
  {
    name: "ZEESEA x British Museum Eyeshadow",
    brand: "ZEESEA",
    subCategory: "Eye Makeup",
    price: 58.0,
    gmv: 175000,
    gmvGrowthRate: 145,
    salesVolume: 3020,
    salesGrowthRate: 130,
    creatorCount: 88,
    creatorGrowthRate: 95,
    videoCount: 310,
    viewCount: 9800000,
    primaryKeyword: "zeesea british museum",
    keywords: '["zeesea","collab eyeshadow","british museum","artistic makeup"]',
    searchVolume: 8200,
    searchTrend: "rising",
    sellerCount: 9,
    imageUrl: "https://placehold.co/400x400/f0f9ff/0369a1?text=ZEESEA",
  },
  {
    name: "Wet n Wild MegaGlo Highlighter",
    brand: "Wet n Wild",
    subCategory: "Face Makeup",
    price: 28.0,
    gmv: 310000,
    gmvGrowthRate: 42,
    salesVolume: 11100,
    salesGrowthRate: 35,
    creatorCount: 420,
    creatorGrowthRate: 28,
    videoCount: 1900,
    viewCount: 41000000,
    primaryKeyword: "highlighter glow",
    keywords: '["highlighter","wet n wild","glow makeup","affordable"]',
    searchVolume: 22000,
    searchTrend: "rising",
    sellerCount: 38,
    imageUrl: "https://placehold.co/400x400/fefce8/eab308?text=WnW",
  },
  {
    name: "JUDYDOLL Orange Fixing Mist Setting Spray",
    brand: "JUDYDOLL",
    subCategory: "Setting Spray",
    price: 35.0,
    gmv: 195000,
    gmvGrowthRate: 78,
    salesVolume: 5600,
    salesGrowthRate: 65,
    creatorCount: 145,
    creatorGrowthRate: 55,
    videoCount: 520,
    viewCount: 16000000,
    primaryKeyword: "setting spray tiktok",
    keywords: '["setting spray","judydoll","makeup fixing","mist"]',
    searchVolume: 14500,
    searchTrend: "rising",
    sellerCount: 22,
    imageUrl: "https://placehold.co/400x400/fff7ed/ea580c?text=JUDYDOLL",
  },
  {
    name: "Flortte Heart Beat Blush Stick",
    brand: "Flortte",
    subCategory: "Blush",
    price: 42.0,
    gmv: 285000,
    gmvGrowthRate: 92,
    salesVolume: 6800,
    salesGrowthRate: 80,
    creatorCount: 230,
    creatorGrowthRate: 68,
    videoCount: 890,
    viewCount: 31000000,
    primaryKeyword: "blush stick",
    keywords: '["blush stick","flortte","cream blush","cheek color"]',
    searchVolume: 19000,
    searchTrend: "rising",
    sellerCount: 18,
    imageUrl: "https://placehold.co/400x400/fff0f6/ec4899?text=Flortte",
  },
  {
    name: "Maybelline Sky High Mascara",
    brand: "Maybelline",
    subCategory: "Eye Makeup",
    price: 35.9,
    gmv: 920000,
    gmvGrowthRate: -5,
    salesVolume: 25600,
    salesGrowthRate: -3,
    creatorCount: 1800,
    creatorGrowthRate: -2,
    videoCount: 8200,
    viewCount: 210000000,
    primaryKeyword: "sky high mascara",
    keywords: '["mascara","maybelline","sky high","lashes"]',
    searchVolume: 78000,
    searchTrend: "stable",
    sellerCount: 220,
    imageUrl: "https://placehold.co/400x400/f8fafc/334155?text=Maybelline",
  },
  {
    name: "INTO YOU Gradient Lip Tint",
    brand: "INTO YOU",
    subCategory: "Lip Makeup",
    price: 29.9,
    gmv: 155000,
    gmvGrowthRate: 58,
    salesVolume: 5200,
    salesGrowthRate: 48,
    creatorCount: 175,
    creatorGrowthRate: 42,
    videoCount: 640,
    viewCount: 18500000,
    primaryKeyword: "lip tint gradient",
    keywords: '["lip tint","into you","gradient lips","korean tint"]',
    searchVolume: 16000,
    searchTrend: "rising",
    sellerCount: 32,
    imageUrl: "https://placehold.co/400x400/fdf2f8/be185d?text=INTOYOU",
  },
  {
    name: "Duovivi Glass Skin Serum Foundation",
    brand: "Duovivi",
    subCategory: "Foundation",
    price: 55.0,
    gmv: 98000,
    gmvGrowthRate: 168,
    salesVolume: 1780,
    salesGrowthRate: 145,
    creatorCount: 62,
    creatorGrowthRate: 120,
    videoCount: 210,
    viewCount: 7200000,
    primaryKeyword: "glass skin foundation",
    keywords: '["glass skin","serum foundation","duovivi","dewy foundation"]',
    searchVolume: 11000,
    searchTrend: "rising",
    sellerCount: 7,
    imageUrl: "https://placehold.co/400x400/f0fdf4/15803d?text=Duovivi",
  },
];

export async function POST() {
  await prisma.product.deleteMany();

  const data = DEMO_PRODUCTS.map((p) => {
    const { score, status } = calcTrendScore({
      gmvGrowthRate: p.gmvGrowthRate,
      salesGrowthRate: p.salesGrowthRate,
      creatorGrowthRate: p.creatorGrowthRate,
      searchVolume: p.searchVolume,
      searchTrend: p.searchTrend,
      sellerCount: p.sellerCount,
    });
    return { ...p, category: "Makeup", currency: "MYR", trendScore: score, trendStatus: status };
  });

  await prisma.product.createMany({ data });
  return NextResponse.json({ seeded: data.length });
}
